= The First Asciidoc example: Subtitle     
Lars Vogel(c) 2016 vogella GmbH                                     
Version 0.2, 17.12.2015                                             
:sectnums:                                                          
:toc:        left                                                   
:toclevels: 4                                                       
:toc-title: My Content                                              
                                                                    
:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./img                                                   

This is the optional preamble (an untitled section body). Useful for
writing simple sectionless documents consisting only of a preamble.

== Modelo Del Dominio
[plantuml, draughtsModeloDominio, svg]
....
class Person {
+ name: string
+ surname: string;
+ birthday: string;
+ deadthDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class Entity {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class Product {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class Category{
+ name: String
}

Product -down-> "*" Person
Product -down-> "*" Entity
Entity o-down-> "*" Person
Product --> "*" Category
Entity --> "*" Category
Person --> "*" Category
Category --> "*" Category

....

== Requisitos

=== Requisitos Funcionales

==== Actores y Casos de Uso
[plantuml, diagramaActoresCasosUso, svg]
....

left to right direction

actor User
usecase readIndex
usecase login
usecase logout
usecase register
usecase readEntity
usecase readPerson
usecase readProduct
usecase readCategory


package writers {
actor Writer
usecase createEntity
usecase createPerson
usecase createProduct
usecase createCategory
usecase updateEntity
usecase updatePerson
usecase updateProduct
usecase deleteEntity
usecase deletePerson
usecase deleteProduct
usecase deleteCategory
usecase editEntity
usecase editPerson
usecase editProduct
usecase asociateCategory
usecase asociatePerson
usecase asociateProduct
usecase asociateEntity
}

User --> readIndex
User --> login
User --> logout
User --> register
User --> readPerson
User --> readEntity
User --> readProduct

readPerson ..> readIndex : <<include>>
readEntity ..> readIndex : <<include>>
readProduct ..> readIndex : <<include>>
readPerson ..> readCategory : <<include>>
readEntity ..> readCategory : <<include>>
readProduct ..> readCategory: <<include>>

User <|-down- Writer
Writer --> createEntity
Writer --> createPerson
Writer --> createProduct
Writer --> createCategory
Writer --> updateEntity
Writer --> updatePerson
Writer --> updateProduct
Writer --> deleteEntity
Writer --> deletePerson
Writer --> deleteProduct
Writer --> deleteCategory



createEntity ..> editPerson : <<include>>
createPerson ..> editEntity : <<include>>
createProduct ..> editProduct : <<include>>
updateEntity ..> editPerson : <<include>>
updatePerson ..> editEntity : <<include>>
updateProduct ..> editProduct : <<include>>
editEntity <.. asociateEntity: <<extends>>
editPerson <.. asociatePerson: <<extends>>
editProduct <.. asociateProduct: <<extends>>
createCategory ..> asociateCategory: <<include>>

editPerson ..> readIndex : <<include>>
editEntity ..> readIndex : <<include>>
editProduct ..> readIndex : <<include>>


....

== Diagrama de contexto
[plantuml, contextDiagram, svg]
....

USER_NOT_LOGGED --> USER_LOGGED : login
USER_LOGGED --> USER_NOT_LOGGED : logout
USER_NOT_LOGGED --> USER_LOGGED : register
USER_LOGGED --> USER_LOGGED : create / delete / update
USER_NOT_LOGGED --> USER_NOT_LOGGED : read
USER_LOGGED -down-> [*]

....

== Diagramas de casos de uso
=== Login

[plantuml, loginUseCase, svg]
....

state " " as State1
state " " as State2


USER_NOT_LOGGED -down-> State1 : User request to login

state c <<choice>>

State1 --> State2 : Systems allows introduce email and password
State2 --> c : User introduce email and password
c -up-> USER_NOT_LOGGED : [email and password incorrect]
c --> USER_LOGGED : [email and password correct]

USER_LOGGED --> [*]

....

=== Logout

[plantuml, logoutUseCase, svg]
....

state " " as State1

USER_LOGGED -down-> State1 : User request to logout

State1 --> USER_NOT_LOGGED : Systems allows to logout

USER_NOT_LOGGED --> [*]
....

=== Register

[plantuml, registerUseCase, svg]
....

state " " as State1
state " " as State2

USER_NOT_LOGGED -down-> State1 : User request to register 
State1 --> State2 : Systems allows to introduce name, surname, email and password


state c <<choice>>

State2 --> c : User introduce name, surname, email and password
c -up-> USER_NOT_LOGGED : [email exist]
c --> USER_LOGGED 
USER_LOGGED --> [*]


....

=== Person
==== Create Person

[plantuml, createPersonUseCase, svg]

....

state ":EditPersonSpecification" as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Person


State1 --> USER_LOGGED_END : Systems shows the created Person
USER_LOGGED_END --> [*]
....

==== Edit Person

[plantuml, editPersonUseCase, svg]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :AsociateCategorySpecification" as State4
state "USER_LOGGED" as USER_LOGGED_END
state " " as State3

USER_LOGGED_START --> State1 : User request to edit a Person
State1 --> State2 : System allows introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki


state d <<choice>>

State2 --> State3 :  User introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki 

State3 --> d : System allows introduce a categoryList
d --> State4 : [user select a Category]
d --> USER_LOGGED_END 


State4 --> USER_LOGGED_END : Systems shows the edited Person
USER_LOGGED_END --> [*]
....

==== Update Person

[plantuml, updatePersonUseCase, svg]

....
state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :EditPersonSpecification " as State3
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to update a Person
State1 -down-> State2 : System allows select the Person to update

state c <<choice>>

State2 -right-> c : User selects a Person to update


c --> State3
c-up-> State2 : [Person to update not found]

State3 --> USER_LOGGED_END : Systems shows the Person updated

USER_LOGGED_END --> [*]
....

==== Delete Person

[plantuml, deletePersonUseCase, svg]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Person
State1 --> State2 : System allows select the Person to delete

state c <<choice>>

State2 --> c : User selects a Person to delete

c -up-> State2 : [Person to delete not found]
c --> USER_LOGGED_END : Systems shows the deleted person
USER_LOGGED_END --> [*]

....

==== Asociate Person

[plantuml, asociatePersonUseCase, svg]

....

state " " as State1
state " " as State2
state " " as State3


state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Person
State1 --> State2: System allow to asociate a Person
State2--> State3: User select the Person to asociate

State3 --> USER_LOGGED_END :  System shows the asociate Person
USER_LOGGED_END --> [*]

....

=== Entity
==== Create Entity

[plantuml, createEntityUseCase, svg]

....

state ":EditEntitySpecification " as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Entity

State1 --> USER_LOGGED_END : Systems shows the created Entity
USER_LOGGED_END --> [*]
....

==== Edit Entity

[plantuml, editEntityUseCase, svg]

....

state " " as State1
state " " as State2
state " :AsociateCategorySpecification" as State4
state " :AsociateProductSpecification" as State6
state " " as State3
state " " as State5
state " " as State7


state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request edit a Entity
State1 --> State2 : System allows introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki, 

state d <<choice>>

State2 --> State3 :  User introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki 

State3--> d : System allows introduce categoryList 
d --> State4 : [user select a Category ]
State4 --> State5
d --> State5

state c <<choice>>

State5 --> c : System allows introduce ProducList
c --> State6 : [user select a Product]
State6 --> State7
c --> State7


State7 -->  USER_LOGGED_END  : Systems shows the edited Person
USER_LOGGED_END --> [*]
....

==== Update Entity

[plantuml, updateEntityUseCase, svg]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :EditEntitySpecification " as State3
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to update a Entity
State1 --> State2 : System allows select to update a Entity

state c <<choice>>

State2 -right-> c : User selects a Entity to update


c --> State3
c-up-> State2 : [Entity to update not found]

State3 --> USER_LOGGED_END : Systems shows the Entity updated

USER_LOGGED_END --> [*]
....

==== Delete Entity

[plantuml, deleteEntityUseCase, svg]

....


state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Entity
State1 --> State2 : System allows select the Entity to delete

state c <<choice>>

State2 --> c : User selects a Entity to delete

c -up-> State2 : [Entity to delete not found]

c --> USER_LOGGED_END : Systems shows the deleted Entity
USER_LOGGED_END --> [*]

....

==== Asociate Entity

[plantuml, asociateEntityUseCase, svg]

....

state " " as State1
state " " as State2
state " " as State3



state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Entity
State1 --> State2: System allow to asociate a Entity
State2--> State3: User select the Entity to asociate

State3 --> USER_LOGGED_END : System shows the asociate Entity
USER_LOGGED_END --> [*]

....

=== Product
==== Create Product

[plantuml, createProductUseCase, svg]

....

state ":EditProductSpecification" as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Product


State1 --> USER_LOGGED_END : Systems shows the created Product
USER_LOGGED_END --> [*]
....


==== Edit Product

[plantuml, editProductUseCase, svg]

....

state " " as State1
state " " as State2
state " " as State3
state " " as State5
state " " as State7
state " " as State9
state " :AsociateCategorySpecification" as State4
state ":AsociatePersonSpecification " as State6
state ":AsociateEntitySpecification " as State8



state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request edit a Entity
State1 --> State2 : System allows introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki, 

state d <<choice>>

State2 --> State3 :  User introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki 

State3--> d : System allows introduce categoryList 
d --> State4 : [user select a Category ]
State4 --> State5
d --> State5

state c <<choice>>

State5 --> c : System allows introduce PersonList
c --> State6 : [user select a Person]
State6 --> State7
c --> State7

state a <<choice>>

State7 --> a : System allows introduce entityList
a --> State8 : [user select a Entity]
State8 --> State9
a --> State9

State9 --> USER_LOGGED_END : System shows the edited Product
USER_LOGGED_END --> [*]
....

==== Update Product

[plantuml, updateProductUseCase, svg]

....


state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :EditProductSpecification " as State3
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to update a Product
State1 -down-> State2 : System allows select the Product to update

state c <<choice>>

State2 -right-> c : User selects a Product to update


c --> State3
c-up-> State2 : [Product to update not found]

State3 --> USER_LOGGED_END : Systems shows the Product updated

USER_LOGGED_END --> [*]
....

==== Delete Product

[plantuml, deleteProductUseCase, svg]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Product
State1 --> State2 : System allows select the Product to delete

state c <<choice>>

State2 --> c : User selects a Product to delete

c -up-> State2 : [Product to delete not found]
c --> USER_LOGGED_END : Systems shows the deleted Product
USER_LOGGED_END --> [*]
....

==== Asociate Product

[plantuml, asociateProductUseCase, svg]

....

state " " as State1
state " " as State2
state " " as State3

state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Product
State1 --> State2: System allow to asociate a Product
State2--> State3: User select the Product to asociate

State3 --> USER_LOGGED_END : System shows the asociate Product
USER_LOGGED_END --> [*]

....

=== Category
==== Create Category

[plantuml, creat CategoryUseCase, svg]

....

state ":EditCategorySpecification " as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Category


State1 --> USER_LOGGED_END : Systems shows the created Category
USER_LOGGED_END --> [*]
....


==== Delete Category

[plantuml, delet CategoryUseCase, svg]

....



state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Category
State1 --> State2 : System allows select the Category to delete

state c <<choice>>

State2 --> c : User selects a Category to delete

c -up-> State2 : [Category to delete not found]

c --> USER_LOGGED_END : Systems shows the deleted Category
USER_LOGGED_END --> [*]

....

==== Asociate Category

[plantuml, asociateCategoryUseCase, svg]

....

state " " as State1
state " " as State2
state " " as State3


state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Category
State1 --> State2: System allow to asociate a Category
State2--> State3: User select the Category to asociate

State3 --> USER_LOGGED_END : System shows the asociate Category
USER_LOGGED_END --> [*]

....

== Analisis

=== Diagrama de clases 
[plantuml, analysisClassDiagram, svg]
....

package "model"{
class PersonModel {
+ name: string
+ surname: string;
+ birthday: string;
+ deadthDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class EntityModel {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class ProductModel {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class CategoryModel{
+ name: String
}

class UserModel{
+ email: String
+ password: String
}
}


ProductModel -down-> "*" PersonModel
ProductModel -down-> "*" EntityModel
EntityModel o-down-> "*" PersonModel
ProductModel --> "*" CategoryModel
EntityModel --> "*" CategoryModel
PersonModel --> "*" CategoryModel
CategoryModel --> "*" CategoryModel

package "controller"{

Class readEntityController
Class readPersonController
Class readProductController
Class readCategoryController
Class createEntityController
Class createPersonController
Class createProductController
Class createCategoryController
Class updateEntityController
Class updatePersonController
Class updateProductController
Class deleteEntityController
Class deletePersonController
Class deleteProductController
Class deleteCategoryController
Class editEntityController
Class editPersonController
Class editProductController
Class asociateCategoryController
Class asociateProductController
Class asociatePersonController
Class asociateEntityController
}

package "view" {

Class LoginView
Class RegisterView
Class HomeView
Class EntityView
Class PersonView
Class ProductView
Class CategoryView
Class EditEntityView
Class EditProductView
Class EditPersonView
Class DetailPersonView
Class DetailEntityView
Class DetailProductView
Class CreatePersonView
Class CreateEntityView
Class CreateProductView
Class CreateCategoryView
}

....
