= The First Asciidoc example: Subtitle     
Lars Vogel(c) 2016 vogella GmbH                                     
Version 0.2, 17.12.2015                                             
:sectnums:                                                          
:toc:        left                                                   
:toclevels: 4                                                       
:toc-title: My Content                                              
                                                                    
:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./img                                                   

This is the optional preamble (an untitled section body). Useful for
writing simple sectionless documents consisting only of a preamble.

== Modelo Del Dominio
[plantuml, draughtsModeloDominio, svg]
....
class Person {
+ name: String
+ birth: Date
+ death: Date
+ image: String
+ wiki: String 
}

class Entity {
+ name: String
+ creationDate: Date
+ wiki: String
}

class Product {
+ name: String
+ creationDate: Date
+ wiki: String
}

class Tag{
+ name: String
}

Product -down-> "*" Person
Product -down-> "*" Entity
Entity o-down-> "*" Person
Tag --> "*" Product
Tag --> "*" Entity
Tag --> "*" Person

....

== Requisitos

=== Requisitos Funcionales

==== Actores y Casos de Uso
[plantuml, diagramaActoresCasosUso, svg]
....

left to right direction

actor User
usecase readIndex

package readers {
actor Reader
usecase readEntity
usecase readPerson
usecase readProduct
}

package writers {
actor Writer
usecase login
usecase createEntity
usecase createPerson
usecase createProduct
usecase updateEntity
usecase updatePerson
usecase updateProduct
usecase deleteEntity
usecase deletePerson
usecase deleteProduct
usecase editEntity
usecase editPerson
usecase editProduct
usecase logout
}

User --> readIndex

User <\|-down- Reader
Reader --> readPerson
Reader --> readEntity
Reader --> readProduct

readPerson ..> readIndex : <<include>>
readEntity ..> readIndex : <<include>>
readProduct ..> readIndex : <<include>>

User <\|-down- Writer
Writer --> login
Writer --> createEntity
Writer --> createPerson
Writer --> createProduct
Writer --> updateEntity
Writer --> updatePerson
Writer --> updateProduct
Writer --> deleteEntity
Writer --> deletePerson
Writer --> deleteProduct
Writer --> logout

createEntity ..> editPerson : <<include>>
createPerson ..> editEntity : <<include>>
createProduct ..> editProduct : <<include>>
updateEntity ..> editPerson : <<include>>
updatePerson ..> editEntity : <<include>>
updateProduct ..> editProduct : <<include>>

editPerson ..> readIndex : <<include>>
editEntity ..> readIndex : <<include>>
editProduct ..> readIndex : <<include>>
....
 

== Third sections
