= The First Asciidoc example: Subtitle     
Lars Vogel(c) 2016 vogella GmbH                                     
Version 0.2, 17.12.2015                                             
:sectnums:                                                          
:toc:        left                                                   
:toclevels: 4                                                       
:toc-title: My Content                                              
                                                                    
:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./img                                                   

This is the optional preamble (an untitled section body). Useful for
writing simple sectionless documents consisting only of a preamble.

== Modelo Del Dominio
[plantuml, draughtsModeloDominio, png]
....
class Person {
+ name: string
+ surname: string;
+ birthday: string;
+ deadthDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class Entity {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class Product {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class Category{
+ name: String
}

Product -down-> "*" Person
Product -down-> "*" Entity
Entity o-down-> "*" Person
Product --> "*" Category
Entity --> "*" Category
Person --> "*" Category
Category --> "*" Category

....

== Requisitos

=== Requisitos Funcionales

==== Actores y Casos de Uso
[plantuml, diagramaActoresCasosUso, png]
....

left to right direction

actor User
usecase readIndex
usecase login
usecase logout
usecase register
usecase readEntity
usecase readPerson
usecase readProduct
usecase readCategory


package writers {
actor Writer
usecase createEntity
usecase createPerson
usecase createProduct
usecase createCategory
usecase updateEntity
usecase updatePerson
usecase updateProduct
usecase deleteEntity
usecase deletePerson
usecase deleteProduct
usecase deleteCategory
usecase editEntity
usecase editPerson
usecase editProduct
usecase asociateCategory
usecase asociatePerson
usecase asociateProduct
usecase asociateEntity
}

User --> readIndex
User --> login
User --> logout
User --> register
User --> readPerson
User --> readEntity
User --> readProduct

readPerson ..> readIndex : <<include>>
readEntity ..> readIndex : <<include>>
readProduct ..> readIndex : <<include>>
readPerson ..> readCategory : <<include>>
readEntity ..> readCategory : <<include>>
readProduct ..> readCategory: <<include>>

User <|-down- Writer
Writer --> createEntity
Writer --> createPerson
Writer --> createProduct
Writer --> createCategory
Writer --> updateEntity
Writer --> updatePerson
Writer --> updateProduct
Writer --> deleteEntity
Writer --> deletePerson
Writer --> deleteProduct
Writer --> deleteCategory



createEntity ..> editEntity : <<include>>
createPerson ..> editPerson : <<include>>
createProduct ..> editProduct : <<include>>
updateEntity ..> editEntity : <<include>>
updatePerson ..> editPerson : <<include>>
updateProduct ..> editProduct : <<include>>
editEntity <.. asociatePerson: <<extends>>
editEntity <.. asociateCategory: <<extends>>

editProduct <.. asociatePerson: <<extends>>
editProduct <.. asociateEntity: <<extends>>


editPerson <.. asociateCategory: <<extends>>

editProduct <.. asociateProduct: <<extends>>
editProduct <.. asociateCategory: <<extends>>

editPerson ..> readIndex : <<include>>
editEntity ..> readIndex : <<include>>
editProduct ..> readIndex : <<include>>


....

== Diagrama de contexto
[plantuml, contextDiagram, png]
....

USER_NOT_LOGGED --> USER_LOGGED : login
USER_LOGGED --> USER_NOT_LOGGED : logout
USER_NOT_LOGGED --> USER_LOGGED : register
USER_LOGGED --> USER_LOGGED : create / delete / update
USER_NOT_LOGGED --> USER_NOT_LOGGED : read
USER_LOGGED -down-> [*]

....

== Diagramas de casos de uso
=== Login

[plantuml, loginUseCase, png]
....

state " " as State1
state " " as State2


USER_NOT_LOGGED -down-> State1 : User request to login

state c <<choice>>

State1 --> State2 : Systems allows introduce email and password
State2 --> c : User introduce email and password
c -up-> USER_NOT_LOGGED : [email and password incorrect]
c --> USER_LOGGED : [email and password correct]

USER_LOGGED --> [*]

....

=== Logout

[plantuml, logoutUseCase, png]
....

state " " as State1

USER_LOGGED -down-> State1 : User request to logout

State1 --> USER_NOT_LOGGED : Systems allows to logout

USER_NOT_LOGGED --> [*]
....

=== Register

[plantuml, registerUseCase, png]
....

state " " as State1
state " " as State2

USER_NOT_LOGGED -down-> State1 : User request to register 
State1 --> State2 : Systems allows to introduce name, surname, email and password


state c <<choice>>

State2 --> c : User introduce name, surname, email and password
c -up-> USER_NOT_LOGGED : [email exist]
c --> USER_LOGGED 
USER_LOGGED --> [*]


....

=== Person
==== Create Person

[plantuml, createPersonUseCase, png]

....

state ":EditPersonSpecification" as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Person


State1 --> USER_LOGGED_END : Systems shows the created Person
USER_LOGGED_END --> [*]
....

==== Edit Person

[plantuml, editPersonUseCase, png]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :AsociateCategorySpecification" as State4
state "USER_LOGGED" as USER_LOGGED_END
state " " as State3

USER_LOGGED_START --> State1 : User request to edit a Person
State1 --> State2 : System allows introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki


state d <<choice>>

State2 --> State3 :  User introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki 

State3 --> d : System allows introduce a categoryList
d --> State4 : [user select a Category]
d --> USER_LOGGED_END 


State4 --> USER_LOGGED_END : Systems shows the edited Person
USER_LOGGED_END --> [*]
....

==== Update Person

[plantuml, updatePersonUseCase, png]

....
state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :EditPersonSpecification " as State3
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to update a Person
State1 -down-> State2 : System allows select the Person to update

state c <<choice>>

State2 -right-> c : User selects a Person to update


c --> State3
c-up-> State2 : [Person to update not found]

State3 --> USER_LOGGED_END : Systems shows the Person updated

USER_LOGGED_END --> [*]
....

==== Delete Person

[plantuml, deletePersonUseCase, png]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Person
State1 --> State2 : System allows select the Person to delete

state c <<choice>>

State2 --> c : User selects a Person to delete

c -up-> State2 : [Person to delete not found]
c --> USER_LOGGED_END : Systems shows the deleted person
USER_LOGGED_END --> [*]

....

==== Asociate Person

[plantuml, asociatePersonUseCase, png]

....

state " " as State1
state " " as State2
state " " as State3


state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Person
State1 --> State2: System allow to asociate a Person
State2--> State3: User select the Person to asociate

State3 --> USER_LOGGED_END :  System shows the asociate Person
USER_LOGGED_END --> [*]

....

=== Entity
==== Create Entity

[plantuml, createEntityUseCase, png]

....

state ":EditEntitySpecification " as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Entity

State1 --> USER_LOGGED_END : Systems shows the created Entity
USER_LOGGED_END --> [*]
....

==== Edit Entity

[plantuml, editEntityUseCase, png]

....

state " " as State1
state " " as State2
state " :AsociateCategorySpecification" as State4
state " :AsociateProductSpecification" as State6
state " " as State3
state " " as State5
state " " as State7


state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request edit a Entity
State1 --> State2 : System allows introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki, 

state d <<choice>>

State2 --> State3 :  User introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki 

State3--> d : System allows introduce categoryList 
d --> State4 : [user select a Category ]
State4 --> State5
d --> State5

state c <<choice>>

State5 --> c : System allows introduce PersonList
c --> State6 : [user select a Person]
State6 --> State7
c --> State7


State7 -->  USER_LOGGED_END  : Systems shows the edited Entity
USER_LOGGED_END --> [*]
....

==== Update Entity

[plantuml, updateEntityUseCase, png]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :EditEntitySpecification " as State3
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to update a Entity
State1 --> State2 : System allows select to update a Entity

state c <<choice>>

State2 -right-> c : User selects a Entity to update


c --> State3
c-up-> State2 : [Entity to update not found]

State3 --> USER_LOGGED_END : Systems shows the Entity updated

USER_LOGGED_END --> [*]
....

==== Delete Entity

[plantuml, deleteEntityUseCase, png]

....


state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Entity
State1 --> State2 : System allows select the Entity to delete

state c <<choice>>

State2 --> c : User selects a Entity to delete

c -up-> State2 : [Entity to delete not found]

c --> USER_LOGGED_END : Systems shows the deleted Entity
USER_LOGGED_END --> [*]

....

==== Asociate Entity

[plantuml, asociateEntityUseCase, png]

....

state " " as State1
state " " as State2
state " " as State3



state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Entity
State1 --> State2: System allow to asociate a Entity
State2--> State3: User select the Entity to asociate

State3 --> USER_LOGGED_END : System shows the asociate Entity
USER_LOGGED_END --> [*]

....

=== Product
==== Create Product

[plantuml, createProductUseCase, png]

....

state ":EditProductSpecification" as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Product


State1 --> USER_LOGGED_END : Systems shows the created Product
USER_LOGGED_END --> [*]
....


==== Edit Product

[plantuml, editProductUseCase, png]

....

state " " as State1
state " " as State2
state " " as State3
state " " as State5
state " " as State7
state " " as State9
state " :AsociateCategorySpecification" as State4
state ":AsociatePersonSpecification " as State6
state ":AsociateEntitySpecification " as State8



state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request edit a Entity
State1 --> State2 : System allows introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki, 

state d <<choice>>

State2 --> State3 :  User introduce name, surname, birthDate, deadthDate, description, urlImage, urlWiki 

State3--> d : System allows introduce categoryList 
d --> State4 : [user select a Category ]
State4 --> State5
d --> State5

state c <<choice>>

State5 --> c : System allows introduce PersonList
c --> State6 : [user select a Person]
State6 --> State7
c --> State7

state a <<choice>>

State7 --> a : System allows introduce EntityList
a --> State8 : [user select a Entity]
State8 --> State9
a --> State9

State9 --> USER_LOGGED_END : System shows the edited Product
USER_LOGGED_END --> [*]
....

==== Update Product

[plantuml, updateProductUseCase, png]

....


state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state " :EditProductSpecification " as State3
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to update a Product
State1 -down-> State2 : System allows select the Product to update

state c <<choice>>

State2 -right-> c : User selects a Product to update


c --> State3
c-up-> State2 : [Product to update not found]

State3 --> USER_LOGGED_END : Systems shows the Product updated

USER_LOGGED_END --> [*]
....

==== Delete Product

[plantuml, deleteProductUseCase, png]

....

state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Product
State1 --> State2 : System allows select the Product to delete

state c <<choice>>

State2 --> c : User selects a Product to delete

c -up-> State2 : [Product to delete not found]
c --> USER_LOGGED_END : Systems shows the deleted Product
USER_LOGGED_END --> [*]
....

==== Asociate Product

[plantuml, asociateProductUseCase, png]

....

state " " as State1
state " " as State2
state " " as State3

state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Product
State1 --> State2: System allow to asociate a Product
State2--> State3: User select the Product to asociate

State3 --> USER_LOGGED_END : System shows the asociate Product
USER_LOGGED_END --> [*]

....

=== Category
==== Create Category

[plantuml, creat CategoryUseCase, png]

....

state ":EditCategorySpecification " as State1
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to create a Category


State1 --> USER_LOGGED_END : Systems shows the created Category
USER_LOGGED_END --> [*]
....


==== Delete Category

[plantuml, delet CategoryUseCase, png]

....



state " " as State1
state " " as State2
state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to delete a Category
State1 --> State2 : System allows select the Category to delete

state c <<choice>>

State2 --> c : User selects a Category to delete

c -up-> State2 : [Category to delete not found]

c --> USER_LOGGED_END : Systems shows the deleted Category
USER_LOGGED_END --> [*]

....

==== Asociate Category

[plantuml, asociateCategoryUseCase, svg]

....

state " " as State1
state " " as State2
state " " as State3


state "USER_LOGGED" as USER_LOGGED_START
state "USER_LOGGED" as USER_LOGGED_END

USER_LOGGED_START --> State1 : User request to asociate a Category
State1 --> State2: System allow to asociate a Category
State2--> State3: User select the Category to asociate

State3 --> USER_LOGGED_END : System shows the asociate Category
USER_LOGGED_END --> [*]

....

== Analisis

=== Diagrama de clases 
[plantuml, analysisClassDiagram, svg]
....

package "model"{
class PersonModel {
+ name: string
+ surname: string;
+ birthday: string;
+ deadthDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class EntityModel {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class ProductModel {
+ name: string
+ creationDate: string;
+ endDate: string;
+ description: string;
+ urlImage: string;
+ urlWiki: string
}

class CategoryModel{
+ name: String
}

class UserModel{
+ email: String
+ password: String
}
}


ProductModel -down-> "*" PersonModel
ProductModel -down-> "*" EntityModel
EntityModel o-down-> "*" PersonModel
ProductModel --> "*" CategoryModel
EntityModel --> "*" CategoryModel
PersonModel --> "*" CategoryModel
CategoryModel --> "*" CategoryModel

package "controller"{
Class loginController
Class registerController

Class readEntityController
Class readPersonController
Class readProductController
Class readCategoryController
Class createEntityController
Class createPersonController
Class createProductController
Class createCategoryController
Class updateEntityController
Class updatePersonController
Class updateProductController
Class deleteEntityController
Class deletePersonController
Class deleteProductController
Class deleteCategoryController
Class editEntityController
Class editPersonController
Class editProductController
Class asociateCategoryController
Class asociateProductController
Class asociatePersonController
Class asociateEntityController
}

package "view" {

Class LoginView
Class RegisterView
Class HomeView
Class EntityView
Class PersonView
Class ProductView
Class CategoryView
Class UpdateEntityView
Class UpdateProductView
Class UpdatePersonView
Class DetailPersonView
Class DetailEntityView
Class DetailProductView
Class CreatePersonView
Class CreateEntityView
Class CreateProductView
Class CreateCategoryView
Class DeletePersonView
Class DeleteProductView
Class DeleteEntityView
Class DeleteCategoryView
}

....

=== Analisis de caso de uso
==== Login
[plantuml, loginAnalisis, svg]
....
left to right direction

actor User
boundary LoginView
control LoginController
entity UserModel

User --> LoginView
LoginView --> LoginController
LoginController --> UserModel
....

[plantuml, loginAnalisisCollaboration, svg]
....
left to right direction

Class User as ":User"
Class LoginView as ":LoginView"
Class LoginController as ":LoginController"
Class UserModel as ":UserModel"

User --> LoginView  : "login() \n setEmail(email) \n setPassword(password)"
LoginView --> LoginController : "login(email, password)"
LoginController --> UserModel : "getUser(email)"
....

==== logout
???

==== Register
[plantuml, registerAnalisis, svg]
....
left to right direction

actor User
boundary RegisterView
control RegisterController
entity UserModel

User --> RegisterView
RegisterView --> RegisterController
RegisterController --> UserModel
....

[plantuml, registerAnalisisCollaboration, svg]
....
left to right direction

class User as ":User"
class RegisterView as ":Registerview"
class RegisterController as ":RegisterController"
class UserModel as ":UserModel"

User --> RegisterView : "register() \n setEmail(email, password)"
RegisterView --> RegisterController : "register(email, password)"
RegisterController --> UserModel : "createUser(email, password)"
....

==== Person
===== CreatePerson
[plantuml, createPersonAnalisis, svg]
....
left to right direction

actor Writer
boundary CreatePersonView
control CreatePersonController
control EditPersonController
control AsociateCategoryController
entity PersonModel
entity CategoryModel

Writer --> CreatePersonView
CreatePersonView --> CreatePersonController
CreatePersonController --> EditPersonController
EditPersonController --> AsociateCategoryController
EditPersonController --> PersonModel
AsociateCategoryController --> CategoryModel
....

[plantuml, createPersonAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class CreatePersonView as ":CreatePersonView"
class CreatePersonController as ":CreatePersonController"
class EditPersonController as ":EditPersonController"
class AsociateCategoryController as ":AsociateCategoryController"
class PersonModel as ":PersonModel"
class CategoryModel as "CategoryModel"

Writer --> CreatePersonView : "createPerson() \n setPersonData(personData)"
CreatePersonView --> CreatePersonController : "createPerson(personData)"
CreatePersonController --> EditPersonController : "createPerson(personData)"
EditPersonController --> AsociateCategoryController : "getCategory()"
EditPersonController --> PersonModel : "createPerson(personData)"
AsociateCategoryController --> CategoryModel : "getCategory()"
....

===== UpdatePerson
[plantuml, updatePersonAnalisis, svg]
....
left to right direction

actor Writer
boundary UpdatePersonView
control ReadPersonController
control UpdatePersonController
control EditPersonController
control AsociateCategoryController
entity CategoryModel
entity PersonModel

Writer --> UpdatePersonView
UpdatePersonView --> ReadPersonController
UpdatePersonView --> UpdatePersonController
UpdatePersonController --> EditPersonController
EditPersonController --> AsociateCategoryController
ReadPersonController --> PersonModel
EditPersonController --> PersonModel
AsociateCategoryController --> CategoryModel
....

[plantuml, updatePersonAnalisisCollaborations, svg]
....
left to right direction

class Writer as ":Writer"
class UpdatePersonView as ":UpdatePersonView"
class ReadPersonController as ":ReadPersonController"
class UpdatePersonController as ":UpdatePersonController"
class EditPersonController as ":EditPersonController"
class AsociateCategoryController as ":AsociateCategoryController"
class CategoryModel as ":CategoryModel"
class PersonModel as ":PersonModel"

Writer --> UpdatePersonView : "updatePerson(personId) \n setPersonData(personData)"
UpdatePersonView --> ReadPersonController : "getPerson(personId)"
UpdatePersonView --> UpdatePersonController : "updatePerson(personData)"
UpdatePersonController --> EditPersonController : "updatePerson(personData)"
EditPersonController --> AsociateCategoryController : "getCategory()"
ReadPersonController --> PersonModel : "getPerson(personId)"
EditPersonController --> PersonModel : "updatePerson(personData)"
AsociateCategoryController --> CategoryModel : "getCategory()"
....

===== DeletePerson
[plantuml, deletePersonAnalisis, svg]
....
left to right direction

actor Writer
boundary DeletePersonView
control ReadPersonController
control DeletePersonController
entity PersonModel

Writer --> DeletePersonView
DeletePersonView --> ReadPersonController
DeletePersonView --> DeletePersonController
ReadPersonController --> PersonModel
DeletePersonController --> PersonModel
....

[plantuml, deletePersonAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class DeletePersonView as ":DeletePersonView"
class ReadPersonController as ":ReadPersonController"
class DeletePersonController as ":DeletePersonController"
class PersonModel as ":PersonModel"

Writer --> DeletePersonView : "deletePerson(personId)"
DeletePersonView --> ReadPersonController : "getPerson(personId)"
DeletePersonView --> DeletePersonController : "deletePerson(personId)"
ReadPersonController --> PersonModel : "getPerson(personId)"
DeletePersonController --> PersonModel : "deletePerson(personId)"
....

==== Product
===== CreateProduct
[plantuml, createProductAnalisis, svg]
....
left to right direction
actor Writer
boundary CreateProductView
control CreateProductController
control EditProductController
control AsociateCategoryController
control AsociatePersonController
control AsociateEntityController
entity CategoryModel
entity ProductModel
entity EntityModel
entity PersonModel

Writer --> CreateProductView
CreateProductView --> CreateProductController
CreateProductController --> EditProductController
EditProductController --> AsociateCategoryController
EditProductController --> AsociatePersonController
EditProductController --> AsociateEntityController
EditProductController --> ProductModel
AsociateCategoryController --> CategoryModel
AsociatePersonController --> PersonModel
AsociateEntityController --> EntityModel
....

[plantuml, createProductAnalisisCollaboration, svg]
....
left to right direction
class Writer as ":Writer"
class CreateProductView as ":CreateProductView"
class CreateProductController as ":CreateProductController"
class EditProductController as ":EditProductController"
class AsociateCategoryController as ":AsociateCategoryController"
class AsociatePersonController as ":AsociatePersonController"
class AsociateEntityController as ":AsociateEntityController"
class CategoryModel as ":CategoryModel"
class ProductModel as ":ProductModel"
class EntityModel as ":EntityModel"
class PersonModel as ":PersonModel"

Writer --> CreateProductView : "createProduct() \n setProductData(productData)"
CreateProductView --> CreateProductController : "createProduct(productData)"
CreateProductController --> EditProductController : "createProduct(productData)"
EditProductController --> AsociateCategoryController : "getCategory()"
EditProductController --> AsociatePersonController : "getProduct()"
EditProductController --> AsociateEntityController : "getEntity()"
EditProductController --> ProductModel : "createProduct(productData)"
AsociateCategoryController --> CategoryModel : "getCategory()"
AsociatePersonController --> PersonModel : "getPerson()"
AsociateEntityController --> EntityModel : "getEntity()"
....

===== updateProduct
[plantuml, updateProductAnalisis, svg]
....
left to right direction

actor Writer
boundary UpdateProductView
control UpdateProductController
control EditProductController
control AsociateCategoryController
control AsociatePersonController
control AsociateEntityController
control ReadProductController
entity CategoryModel
entity ProductModel
entity EntityModel
entity PersonModel

Writer --> UpdateProductView
UpdateProductView --> UpdateProductController
UpdateProductController --> EditProductController
UpdateProductController --> ReadProductController
EditProductController --> AsociateCategoryController
EditProductController --> AsociatePersonController
EditProductController --> AsociateEntityController
EditProductController --> ProductModel
AsociateCategoryController --> CategoryModel
AsociatePersonController --> PersonModel
AsociateEntityController --> EntityModel
ReadProductController --> ProductModel
....

[plantuml, updateProductAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class UpdateProductView as ":UpdateProductView"
class UpdateProductController as ":UpdateProductController"
class EditProductController as ":EditProductController"
class AsociateCategoryController as ":AsociateCategoryController"
class AsociatePersonController as ":AsociatePersonController"
class AsociateEntityController as ":AsociateEntityController"
class ReadProductController as ":ReadProductController"
class CategoryModel as ":CategoryModel"
class ProductModel as ":ProductModel"
class EntityModel as ":EntityModel"
class PersonModel as ":PersonModel"

Writer --> UpdateProductView : "updateProduct() \n setProductData(productData)"
UpdateProductView --> UpdateProductController : "updateProduct(productData)"
UpdateProductController --> EditProductController : "updateProduct(productData)"
UpdateProductController --> ReadProductController : "getProduct(productId)"
EditProductController --> AsociateCategoryController : "getCategory()"
EditProductController --> AsociatePersonController : "getPerson()"
EditProductController --> AsociateEntityController : "getEntity()"
EditProductController --> ProductModel : "updateProduct(productData)"
AsociateCategoryController --> CategoryModel : "getCategory()"
AsociatePersonController --> PersonModel : "getPerson()"
AsociateEntityController --> EntityModel : "getEntity()"
ReadProductController --> ProductModel : "getProduct(productId)"
....

===== DeleteProduct
[plantuml, deleteProductAnalisis, svg]
....
left to right direction

actor Writer
boundary DeleteProductView
control ReadProductController
control DeleteProductController
entity PersonModel

Writer --> DeleteProductView
DeleteProductView --> ReadProductController
DeleteProductView --> DeleteProductController
ReadProductController --> PersonModel
DeleteProductController --> PersonModel
....

[plantuml, deleteProductAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class DeleteProductView as ":DeleteProductView"
class ReadProductController as ":ReadProductController"
class DeleteProductController as ":DeleteProductController"
class PersonModel as ":PersonModel"

Writer --> DeleteProductView : "deleteProduct(productId)"
DeleteProductView --> ReadProductController : "getProduct(productId)"
DeleteProductView --> DeleteProductController : "deleteProduct(productId)"
ReadProductController --> PersonModel : "getProduct(productId)"
DeleteProductController --> PersonModel : "deleteProduct(productId)"
....

==== Entity
===== CreateEntity

[plantuml, createEntityAnalisis, svg]
....
left to right direction

actor Writer
boundary CreateEntityView
control CreateEntityController
control AsociateCategoryController
control AsociatePersonController
entity CategoryModel
entity PersonModel
entity EntityModel


Writer --> CreateEntityView
CreateEntityView --> CreateEntityController
CreateEntityController --> EditEntityController
EditEntityController --> AsociateCategoryController
EditEntityController --> AsociatePersonController
EditEntityController --> EntityModel
AsociateCategoryController --> CategoryModel
AsociatePersonController --> PersonModel
....

[plantuml, createEntityAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class CreateEntityView as ":CreateEntityView"
class CreateEntityController as ":CreateEntityController"
class AsociateCategoryController as ":AsociateCategoryController"
class AsociatePersonController as ":AsociatePersonController"
class CategoryModel as ":CategoryModel"
class PersonModel as ":PersonModel"
class EntityModel as ":EntityModel"


Writer --> CreateEntityView : "createEntity() \n setEntityData(entityData)"
CreateEntityView --> CreateEntityController : "createEntity(entityData)"
CreateEntityController --> EditEntityController : "createEntity(entityData)"
EditEntityController --> AsociateCategoryController : "getCategory()"
EditEntityController --> AsociatePersonController : "getperson()"
EditEntityController --> EntityModel : "createEntity(entityData)"
AsociateCategoryController --> CategoryModel : "getCategory()"
AsociatePersonController --> PersonModel : "getPerson()"
....

===== UpdateEntity

[plantuml, updateEntityAnalisis, svg]
....
left to right direction

actor Writer
boundary UpdateEntityView
control UpdateEntityController
control ReadEntityController
control AsociateCategoryController
control AsociatePersonController
entity CategoryModel
entity PersonModel
entity EntityModel

Writer --> UpdateEntityView
UpdateEntityView --> UpdateEntityController
UpdateEntityController --> EditEntityController
EditEntityController --> AsociateCategoryController
EditEntityController --> AsociatePersonController
UpdateEntityController --> ReadEntityController
EditEntityController --> EntityModel
UpdateEntityController --> EntityModel
AsociateCategoryController --> CategoryModel
AsociatePersonController --> PersonModel
ReadEntityController --> EntityModel
....

[plantuml, updateEntityAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class UpdateEntityView as ":UpdateEntityView"
class UpdateEntityController as ":UpdateEntityController"
class ReadEntityController as ":ReadEntityController"
class AsociateCategoryController as ":AsociateCategoryController"
class AsociatePersonController as ":AsociatePersonController"
class CategoryModel as ":CategoryModel"
class CategoryModel as ":CategoryModel"
class EntityModel as ":EntityModel"

Writer --> UpdateEntityView : "updateEntity() \n setEntityData(entityData)"
UpdateEntityView --> UpdateEntityController : "updateEntity(entityData)"
UpdateEntityController --> EditEntityController : "updateEntity(entityData)"
EditEntityController --> AsociateCategoryController : "getCategory()"
EditEntityController --> AsociatePersonController : "getPerson()"
UpdateEntityController --> ReadEntityController : "getEntity()"
EditEntityController --> EntityModel : "updateEntity(entityData)"
AsociateCategoryController --> CategoryModel : "getCategory()"
AsociatePersonController --> PersonModel : "getPerson()"
ReadEntityController --> EntityModel : "getEntity"
....

===== DeleteEntity
[plantuml, deleteEntityAnalisis, svg]
....
left to right direction

actor Writer
boundary DeleteEntityView
control ReadEntityController
control DeleteEntityController
entity EntityModel

Writer --> DeleteEntityView
DeleteEntityView --> ReadEntityController
DeleteEntityView --> DeleteEntityController
ReadEntityController --> EntityModel
DeleteEntityController --> EntityModel
....

[plantuml, deleteEntityAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class DeleteEntityView as ":DeleteEntityView"
class ReadEntityController as ":ReadEntityController"
class DeleteEntityController as ":DeleteEntityController"
class EntityModel as ":EntityModel"

Writer --> DeleteEntityView : "deleteEntity(entityId)"
DeleteEntityView --> ReadEntityController : "getEntity(entityId)"
DeleteEntityView --> DeleteEntityController : "deleteEntity(entityId)"
ReadEntityController --> EntityModel : "getEntity(entityId)"
DeleteEntityController --> EntityModel : "deleteEntity(entityId)"
....

==== Category
===== CreateCategory
[plantuml, createCategoryAnalisis, svg]
....
left to right direction

actor Writter
boundary CreateCategoryView
control CreateCategoryController
entity CategoryModel

Writter --> CreateCategoryView
CreateCategoryView --> CreateCategoryController
CreateCategoryController --> CategoryModel
....

[plantuml, createCategoryAnalisisCollaboration, svg]
....
left to right direction

class Writter as ":Writer"
class CreateCategoryView as ":CreateCategoryView"
class CreateCategoryController as ":CreateCategoryController"
class CategoryModel as ":CategoryModel"

Writter --> CreateCategoryView : "createCagegory() \n setCategoryData(categoryData)"
CreateCategoryView --> CreateCategoryController : "createCategory(categoryData)"
CreateCategoryController --> CategoryModel : "createCategory(categoryData)"
....

===== DeleteCategory
[plantuml, deleteCategoryAnalisis, svg]
....
left to right direction

actor Writer
boundary DeleteCategoryView
control DeleteCategoryController
control ReadCategoryController
entity CategoryModel

Writer --> DeleteCategoryView
DeleteCategoryView --> DeleteCategoryController
DeleteCategoryView --> ReadCategoryController
ReadCategoryController --> CategoryModel
DeleteCategoryController --> CategoryModel
....

[plantuml, deleteCategoryAnalisisCollaboration, svg]
....
left to right direction

class Writer as ":Writer"
class DeleteCategoryView as ":DeleteCategoryView"
class DeleteCategoryController as ":DeleteCategoryController"
class ReadCategoryController as ":ReadCategoryController"
class CategoryModel as ":CategoryModel"

Writer --> DeleteCategoryView : "deleteCategory(categoryId)"
DeleteCategoryView --> DeleteCategoryController : "deleteCategory(categoryId)"
DeleteCategoryView --> ReadCategoryController : "getCategory(categoryId)"
ReadCategoryController --> CategoryModel : "getCategory(categoryId)"
DeleteCategoryController --> CategoryModel : "deleteCategory(categoryId)"
....